authors:
  buckse:
    name: Sebastian Buck
    description: Autor und Experte für Verkehrs- und Mobilitätsthemen mit Schwerpunkt auf Verkehrssimulation und Analyse.
    avatar: assets/img/team/sebastian_author.webp
